apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies-service
  namespace: merchprint
  labels:
    app: companies-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: companies-service
  template:
    metadata:
      labels:
        app: companies-service
    spec:
      containers:
        - name: companies-service
          image: merchprint/companies-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: RMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: RMQ_URL
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: companies-service-secret
                  key: DB_URI
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
