apiVersion: v1
kind: Secret
metadata:
  name: companies-service-secret
  namespace: merchprint
type: Opaque
stringData:
  DB_URI: mongodb://companies_user:companies_pass@companies-service-db:27017/companies_db?authSource=admin
