apiVersion: v1
kind: Service
metadata:
  name: companies-service
  namespace: merchprint
  labels:
    app: companies-service
spec:
  selector:
    app: companies-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
