apiVersion: v1
kind: Secret
metadata:
  name: events-service-secret
  namespace: merchprint
type: Opaque
stringData:
  DB_URI: mongodb://events_user:events_pass@events-service-db:27017/events_db?authSource=admin
