apiVersion: v1
kind: Service
metadata:
  name: events-service-db
  namespace: merchprint
  labels:
    app: events-service-db
spec:
  selector:
    app: events-service-db
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  type: ClusterIP
