apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: merchprint
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          # TODO: Actualiza la imagen al registry donde publiques tus imágenes
          image: merchprint/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: RMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: RMQ_URL
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
