apiVersion: v1
kind: Secret
metadata:
  name: orders-service-secret
  namespace: merchprint
type: Opaque
stringData:
  DB_URI: mongodb://orders_user:orders_pass@orders-service-db:27017/orders_db?authSource=admin
