// tokens.ts

export const EVENT_REPOSITORY = Symbol('EVENT_REPOSITORY');

export const REQUIREMENTS_REPOSITORY = Symbol('REQUIREMENTS_REPOSITORY');

export const AUCTION_REPOSITORY = Symbol('AUCTION_REPOSITORY');